#!/bin/bash

mkdir -p AL && ln 16RCA* AL
mkdir -p AL && ln 16RCU* AL
mkdir -p AL && ln 16RCV* AL
mkdir -p AL && ln 16RDA* AL
mkdir -p AL && ln 16RDU* AL
mkdir -p AL && ln 16RDV* AL
mkdir -p AL && ln 16REA* AL
mkdir -p AL && ln 16REV* AL
mkdir -p AL && ln 16RFA* AL
mkdir -p AL && ln 16RFV* AL
mkdir -p AL && ln 16SCA* AL
mkdir -p AL && ln 16SCB* AL
mkdir -p AL && ln 16SCC* AL
mkdir -p AL && ln 16SCD* AL
mkdir -p AL && ln 16SDA* AL
mkdir -p AL && ln 16SDB* AL
mkdir -p AL && ln 16SDC* AL
mkdir -p AL && ln 16SDD* AL
mkdir -p AL && ln 16SEA* AL
mkdir -p AL && ln 16SEB* AL
mkdir -p AL && ln 16SEC* AL
mkdir -p AL && ln 16SED* AL
mkdir -p AL && ln 16SFA* AL
mkdir -p AL && ln 16SFB* AL
mkdir -p AL && ln 16SFC* AL
mkdir -p AL && ln 16SFD* AL
mkdir -p AR && ln 15SUA* AR
mkdir -p AR && ln 15SUT* AR
mkdir -p AR && ln 15SUU* AR
mkdir -p AR && ln 15SUV* AR
mkdir -p AR && ln 15SVA* AR
mkdir -p AR && ln 15SVS* AR
mkdir -p AR && ln 15SVT* AR
mkdir -p AR && ln 15SVU* AR
mkdir -p AR && ln 15SVV* AR
mkdir -p AR && ln 15SWA* AR
mkdir -p AR && ln 15SWS* AR
mkdir -p AR && ln 15SWT* AR
mkdir -p AR && ln 15SWU* AR
mkdir -p AR && ln 15SWV* AR
mkdir -p AR && ln 15SXA* AR
mkdir -p AR && ln 15SXS* AR
mkdir -p AR && ln 15SXT* AR
mkdir -p AR && ln 15SXU* AR
mkdir -p AR && ln 15SXV* AR
mkdir -p AR && ln 15SYA* AR
mkdir -p AR && ln 15SYT* AR
mkdir -p AR && ln 15SYU* AR
mkdir -p AR && ln 15SYV* AR
mkdir -p AR && ln 16SBE* AR
mkdir -p AZ && ln 11SQA* AZ
mkdir -p AZ && ln 11SQR* AZ
mkdir -p AZ && ln 11SQS* AZ
mkdir -p AZ && ln 11SQT* AZ
mkdir -p AZ && ln 11SQU* AZ
mkdir -p AZ && ln 11SQV* AZ
mkdir -p AZ && ln 12RTA* AZ
mkdir -p AZ && ln 12RUA* AZ
mkdir -p AZ && ln 12RVA* AZ
mkdir -p AZ && ln 12RVV* AZ
mkdir -p AZ && ln 12RWA* AZ
mkdir -p AZ && ln 12RWV* AZ
mkdir -p AZ && ln 12RXA* AZ
mkdir -p AZ && ln 12RXV* AZ
mkdir -p AZ && ln 12STA* AZ
mkdir -p AZ && ln 12STB* AZ
mkdir -p AZ && ln 12STC* AZ
mkdir -p AZ && ln 12STD* AZ
mkdir -p AZ && ln 12STE* AZ
mkdir -p AZ && ln 12STF* AZ
mkdir -p AZ && ln 12SUA* AZ
mkdir -p AZ && ln 12SUB* AZ
mkdir -p AZ && ln 12SUC* AZ
mkdir -p AZ && ln 12SUD* AZ
mkdir -p AZ && ln 12SUE* AZ
mkdir -p AZ && ln 12SUF* AZ
mkdir -p AZ && ln 12SVA* AZ
mkdir -p AZ && ln 12SVB* AZ
mkdir -p AZ && ln 12SVC* AZ
mkdir -p AZ && ln 12SVD* AZ
mkdir -p AZ && ln 12SVE* AZ
mkdir -p AZ && ln 12SVF* AZ
mkdir -p AZ && ln 12SWA* AZ
mkdir -p AZ && ln 12SWB* AZ
mkdir -p AZ && ln 12SWC* AZ
mkdir -p AZ && ln 12SWD* AZ
mkdir -p AZ && ln 12SWE* AZ
mkdir -p AZ && ln 12SWF* AZ
mkdir -p AZ && ln 12SXA* AZ
mkdir -p AZ && ln 12SXB* AZ
mkdir -p AZ && ln 12SXC* AZ
mkdir -p AZ && ln 12SXD* AZ
mkdir -p AZ && ln 12SXE* AZ
mkdir -p AZ && ln 12SXF* AZ
mkdir -p CA && ln 10SDG* CA
mkdir -p CA && ln 10SDH* CA
mkdir -p CA && ln 10SDJ* CA
mkdir -p CA && ln 10SDK* CA
mkdir -p CA && ln 10SEF* CA
mkdir -p CA && ln 10SEG* CA
mkdir -p CA && ln 10SEH* CA
mkdir -p CA && ln 10SEJ* CA
mkdir -p CA && ln 10SEK* CA
mkdir -p CA && ln 10SFD* CA
mkdir -p CA && ln 10SFE* CA
mkdir -p CA && ln 10SFF* CA
mkdir -p CA && ln 10SFG* CA
mkdir -p CA && ln 10SFH* CA
mkdir -p CA && ln 10SFJ* CA
mkdir -p CA && ln 10SFK* CA
mkdir -p CA && ln 10SGC* CA
mkdir -p CA && ln 10SGD* CA
mkdir -p CA && ln 10SGE* CA
mkdir -p CA && ln 10SGF* CA
mkdir -p CA && ln 10SGG* CA
mkdir -p CA && ln 10SGH* CA
mkdir -p CA && ln 10SGJ* CA
mkdir -p CA && ln 10SGK* CA
mkdir -p CA && ln 10TCK* CA
mkdir -p CA && ln 10TCL* CA
mkdir -p CA && ln 10TCM* CA
mkdir -p CA && ln 10TDK* CA
mkdir -p CA && ln 10TDL* CA
mkdir -p CA && ln 10TDM* CA
mkdir -p CA && ln 10TEK* CA
mkdir -p CA && ln 10TEL* CA
mkdir -p CA && ln 10TEM* CA
mkdir -p CA && ln 10TFK* CA
mkdir -p CA && ln 10TFL* CA
mkdir -p CA && ln 10TFM* CA
mkdir -p CA && ln 10TGK* CA
mkdir -p CA && ln 10TGL* CA
mkdir -p CA && ln 10TGM* CA
mkdir -p CA && ln 11SKA* CA
mkdir -p CA && ln 11SKB* CA
mkdir -p CA && ln 11SKC* CA
mkdir -p CA && ln 11SKD* CA
mkdir -p CA && ln 11SKE* CA
mkdir -p CA && ln 11SKS* CA
mkdir -p CA && ln 11SKT* CA
mkdir -p CA && ln 11SKU* CA
mkdir -p CA && ln 11SKV* CA
mkdir -p CA && ln 11SLA* CA
mkdir -p CA && ln 11SLB* CA
mkdir -p CA && ln 11SLC* CA
mkdir -p CA && ln 11SLS* CA
mkdir -p CA && ln 11SLT* CA
mkdir -p CA && ln 11SLU* CA
mkdir -p CA && ln 11SLV* CA
mkdir -p CA && ln 11SMA* CA
mkdir -p CA && ln 11SMB* CA
mkdir -p CA && ln 11SMR* CA
mkdir -p CA && ln 11SMS* CA
mkdir -p CA && ln 11SMT* CA
mkdir -p CA && ln 11SMU* CA
mkdir -p CA && ln 11SMV* CA
mkdir -p CA && ln 11SNA* CA
mkdir -p CA && ln 11SNS* CA
mkdir -p CA && ln 11SNT* CA
mkdir -p CA && ln 11SNU* CA
mkdir -p CA && ln 11SNV* CA
mkdir -p CA && ln 11SPS* CA
mkdir -p CA && ln 11SPT* CA
mkdir -p CA && ln 11SPU* CA
mkdir -p CA && ln 11SPV* CA
mkdir -p CA && ln 11SQS* CA
mkdir -p CA && ln 11SQT* CA
mkdir -p CA && ln 11SQU* CA
mkdir -p CA && ln 11TKE* CA
mkdir -p CA && ln 11TKF* CA
mkdir -p CA && ln 11TKG* CA
mkdir -p CO && ln 12SXF* CO
mkdir -p CO && ln 12SXG* CO
mkdir -p CO && ln 12SXH* CO
mkdir -p CO && ln 12SXJ* CO
mkdir -p CO && ln 12SXK* CO
mkdir -p CO && ln 12SYF* CO
mkdir -p CO && ln 12SYG* CO
mkdir -p CO && ln 12SYH* CO
mkdir -p CO && ln 12SYJ* CO
mkdir -p CO && ln 12SYK* CO
mkdir -p CO && ln 12TXK* CO
mkdir -p CO && ln 12TXL* CO
mkdir -p CO && ln 12TYK* CO
mkdir -p CO && ln 12TYL* CO
mkdir -p CO && ln 13SBA* CO
mkdir -p CO && ln 13SBB* CO
mkdir -p CO && ln 13SBC* CO
mkdir -p CO && ln 13SBD* CO
mkdir -p CO && ln 13SBE* CO
mkdir -p CO && ln 13SCA* CO
mkdir -p CO && ln 13SCB* CO
mkdir -p CO && ln 13SCC* CO
mkdir -p CO && ln 13SCD* CO
mkdir -p CO && ln 13SCE* CO
mkdir -p CO && ln 13SDA* CO
mkdir -p CO && ln 13SDB* CO
mkdir -p CO && ln 13SDC* CO
mkdir -p CO && ln 13SDD* CO
mkdir -p CO && ln 13SDE* CO
mkdir -p CO && ln 13SEA* CO
mkdir -p CO && ln 13SEB* CO
mkdir -p CO && ln 13SEC* CO
mkdir -p CO && ln 13SED* CO
mkdir -p CO && ln 13SEE* CO
mkdir -p CO && ln 13SFA* CO
mkdir -p CO && ln 13SFB* CO
mkdir -p CO && ln 13SFC* CO
mkdir -p CO && ln 13SFD* CO
mkdir -p CO && ln 13SFE* CO
mkdir -p CO && ln 13SGA* CO
mkdir -p CO && ln 13SGB* CO
mkdir -p CO && ln 13SGC* CO
mkdir -p CO && ln 13SGD* CO
mkdir -p CO && ln 13SGE* CO
mkdir -p CO && ln 13TBE* CO
mkdir -p CO && ln 13TBF* CO
mkdir -p CO && ln 13TCE* CO
mkdir -p CO && ln 13TCF* CO
mkdir -p CO && ln 13TDE* CO
mkdir -p CO && ln 13TDF* CO
mkdir -p CO && ln 13TEE* CO
mkdir -p CO && ln 13TEF* CO
mkdir -p CO && ln 13TFE* CO
mkdir -p CO && ln 13TFF* CO
mkdir -p CO && ln 13TGE* CO
mkdir -p CO && ln 13TGF* CO
mkdir -p CT && ln 18TXL* CT
mkdir -p CT && ln 18TXM* CT
mkdir -p CT && ln 18TYL* CT
mkdir -p CT && ln 18TYM* CT
mkdir -p CT && ln 19TBF* CT
mkdir -p CT && ln 19TBG* CT
mkdir -p DC && ln 18SUH* DC
mkdir -p DC && ln 18SUJ* DC
mkdir -p DE && ln 18SVH* DE
mkdir -p DE && ln 18SVJ* DE
mkdir -p DE && ln 18SVK* DE
mkdir -p FL && ln 16RDU* FL
mkdir -p FL && ln 16RDV* FL
mkdir -p FL && ln 16REU* FL
mkdir -p FL && ln 16REV* FL
mkdir -p FL && ln 16RFT* FL
mkdir -p FL && ln 16RFU* FL
mkdir -p FL && ln 16RFV* FL
mkdir -p FL && ln 16RGT* FL
mkdir -p FL && ln 16RGU* FL
mkdir -p FL && ln 16RGV* FL
mkdir -p FL && ln 17RKN* FL
mkdir -p FL && ln 17RKP* FL
mkdir -p FL && ln 17RLH* FL
mkdir -p FL && ln 17RLK* FL
mkdir -p FL && ln 17RLL* FL
mkdir -p FL && ln 17RLM* FL
mkdir -p FL && ln 17RLN* FL
mkdir -p FL && ln 17RLP* FL
mkdir -p FL && ln 17RMH* FL
mkdir -p FL && ln 17RMJ* FL
mkdir -p FL && ln 17RMK* FL
mkdir -p FL && ln 17RML* FL
mkdir -p FL && ln 17RMM* FL
mkdir -p FL && ln 17RMN* FL
mkdir -p FL && ln 17RMP* FL
mkdir -p FL && ln 17RMQ* FL
mkdir -p FL && ln 17RNH* FL
mkdir -p FL && ln 17RNJ* FL
mkdir -p FL && ln 17RNK* FL
mkdir -p FL && ln 17RNL* FL
mkdir -p FL && ln 17RNM* FL
mkdir -p FL && ln 17RNN* FL
mkdir -p GA && ln 16RFA* GA
mkdir -p GA && ln 16RFV* GA
mkdir -p GA && ln 16RGA* GA
mkdir -p GA && ln 16RGU* GA
mkdir -p GA && ln 16RGV* GA
mkdir -p GA && ln 16SFA* GA
mkdir -p GA && ln 16SFB* GA
mkdir -p GA && ln 16SFC* GA
mkdir -p GA && ln 16SFD* GA
mkdir -p GA && ln 16SGA* GA
mkdir -p GA && ln 16SGB* GA
mkdir -p GA && ln 16SGC* GA
mkdir -p GA && ln 16SGD* GA
mkdir -p GA && ln 17RKP* GA
mkdir -p GA && ln 17RKQ* GA
mkdir -p GA && ln 17RKR* GA
mkdir -p GA && ln 17RLP* GA
mkdir -p GA && ln 17RLQ* GA
mkdir -p GA && ln 17RLR* GA
mkdir -p GA && ln 17RMP* GA
mkdir -p GA && ln 17RMQ* GA
mkdir -p GA && ln 17RMR* GA
mkdir -p GA && ln 17RNR* GA
mkdir -p GA && ln 17SKR* GA
mkdir -p GA && ln 17SKS* GA
mkdir -p GA && ln 17SKT* GA
mkdir -p GA && ln 17SKU* GA
mkdir -p GA && ln 17SLR* GA
mkdir -p GA && ln 17SLS* GA
mkdir -p GA && ln 17SLT* GA
mkdir -p GA && ln 17SLU* GA
mkdir -p GA && ln 17SMR* GA
mkdir -p GA && ln 17SMS* GA
mkdir -p GA && ln 17SMT* GA
mkdir -p GA && ln 17SNR* GA
mkdir -p IA && ln 14TPN* IA
mkdir -p IA && ln 14TPP* IA
mkdir -p IA && ln 14TQL* IA
mkdir -p IA && ln 14TQM* IA
mkdir -p IA && ln 14TQN* IA
mkdir -p IA && ln 14TQP* IA
mkdir -p IA && ln 15TTE* IA
mkdir -p IA && ln 15TTF* IA
mkdir -p IA && ln 15TTG* IA
mkdir -p IA && ln 15TTH* IA
mkdir -p IA && ln 15TTJ* IA
mkdir -p IA && ln 15TUE* IA
mkdir -p IA && ln 15TUF* IA
mkdir -p IA && ln 15TUG* IA
mkdir -p IA && ln 15TUH* IA
mkdir -p IA && ln 15TUJ* IA
mkdir -p IA && ln 15TVE* IA
mkdir -p IA && ln 15TVF* IA
mkdir -p IA && ln 15TVG* IA
mkdir -p IA && ln 15TVH* IA
mkdir -p IA && ln 15TVJ* IA
mkdir -p IA && ln 15TWE* IA
mkdir -p IA && ln 15TWF* IA
mkdir -p IA && ln 15TWG* IA
mkdir -p IA && ln 15TWH* IA
mkdir -p IA && ln 15TWJ* IA
mkdir -p IA && ln 15TXE* IA
mkdir -p IA && ln 15TXF* IA
mkdir -p IA && ln 15TXG* IA
mkdir -p IA && ln 15TXH* IA
mkdir -p IA && ln 15TXJ* IA
mkdir -p IA && ln 15TYF* IA
mkdir -p IA && ln 15TYG* IA
mkdir -p IA && ln 15TYH* IA
mkdir -p ID && ln 11TMG* ID
mkdir -p ID && ln 11TMH* ID
mkdir -p ID && ln 11TMJ* ID
mkdir -p ID && ln 11TMK* ID
mkdir -p ID && ln 11TMM* ID
mkdir -p ID && ln 11TMN* ID
mkdir -p ID && ln 11TMP* ID
mkdir -p ID && ln 11TNG* ID
mkdir -p ID && ln 11TNH* ID
mkdir -p ID && ln 11TNJ* ID
mkdir -p ID && ln 11TNK* ID
mkdir -p ID && ln 11TNL* ID
mkdir -p ID && ln 11TNM* ID
mkdir -p ID && ln 11TNN* ID
mkdir -p ID && ln 11TNP* ID
mkdir -p ID && ln 11TPG* ID
mkdir -p ID && ln 11TPH* ID
mkdir -p ID && ln 11TPJ* ID
mkdir -p ID && ln 11TPK* ID
mkdir -p ID && ln 11TPL* ID
mkdir -p ID && ln 11TPM* ID
mkdir -p ID && ln 11TPN* ID
mkdir -p ID && ln 11TQG* ID
mkdir -p ID && ln 11TQH* ID
mkdir -p ID && ln 11TQJ* ID
mkdir -p ID && ln 11TQK* ID
mkdir -p ID && ln 11TQL* ID
mkdir -p ID && ln 11TQM* ID
mkdir -p ID && ln 11UMP* ID
mkdir -p ID && ln 11UMQ* ID
mkdir -p ID && ln 11UNP* ID
mkdir -p ID && ln 11UNQ* ID
mkdir -p ID && ln 12TTM* ID
mkdir -p ID && ln 12TTN* ID
mkdir -p ID && ln 12TTP* ID
mkdir -p ID && ln 12TTQ* ID
mkdir -p ID && ln 12TTR* ID
mkdir -p ID && ln 12TUM* ID
mkdir -p ID && ln 12TUN* ID
mkdir -p ID && ln 12TUP* ID
mkdir -p ID && ln 12TUQ* ID
mkdir -p ID && ln 12TVM* ID
mkdir -p ID && ln 12TVN* ID
mkdir -p ID && ln 12TVP* ID
mkdir -p ID && ln 12TVQ* ID
mkdir -p IL && ln 15SXD* IL
mkdir -p IL && ln 15SXE* IL
mkdir -p IL && ln 15SYC* IL
mkdir -p IL && ln 15SYD* IL
mkdir -p IL && ln 15SYE* IL
mkdir -p IL && ln 15TXE* IL
mkdir -p IL && ln 15TXF* IL
mkdir -p IL && ln 15TXH* IL
mkdir -p IL && ln 15TYE* IL
mkdir -p IL && ln 15TYF* IL
mkdir -p IL && ln 15TYG* IL
mkdir -p IL && ln 15TYH* IL
mkdir -p IL && ln 16SBF* IL
mkdir -p IL && ln 16SBG* IL
mkdir -p IL && ln 16SBH* IL
mkdir -p IL && ln 16SBJ* IL
mkdir -p IL && ln 16SBK* IL
mkdir -p IL && ln 16SCF* IL
mkdir -p IL && ln 16SCG* IL
mkdir -p IL && ln 16SCH* IL
mkdir -p IL && ln 16SCJ* IL
mkdir -p IL && ln 16SCK* IL
mkdir -p IL && ln 16SDG* IL
mkdir -p IL && ln 16SDH* IL
mkdir -p IL && ln 16SDJ* IL
mkdir -p IL && ln 16SDK* IL
mkdir -p IL && ln 16TBK* IL
mkdir -p IL && ln 16TBL* IL
mkdir -p IL && ln 16TBM* IL
mkdir -p IL && ln 16TBN* IL
mkdir -p IL && ln 16TCK* IL
mkdir -p IL && ln 16TCL* IL
mkdir -p IL && ln 16TCM* IL
mkdir -p IL && ln 16TCN* IL
mkdir -p IL && ln 16TDK* IL
mkdir -p IL && ln 16TDL* IL
mkdir -p IL && ln 16TDM* IL
mkdir -p IL && ln 16TDN* IL
mkdir -p IN && ln 16SDG* IN
mkdir -p IN && ln 16SDH* IN
mkdir -p IN && ln 16SDJ* IN
mkdir -p IN && ln 16SDK* IN
mkdir -p IN && ln 16SEG* IN
mkdir -p IN && ln 16SEH* IN
mkdir -p IN && ln 16SEJ* IN
mkdir -p IN && ln 16SEK* IN
mkdir -p IN && ln 16SFH* IN
mkdir -p IN && ln 16SFJ* IN
mkdir -p IN && ln 16SFK* IN
mkdir -p IN && ln 16TDK* IN
mkdir -p IN && ln 16TDL* IN
mkdir -p IN && ln 16TDM* IN
mkdir -p IN && ln 16TEK* IN
mkdir -p IN && ln 16TEL* IN
mkdir -p IN && ln 16TEM* IN
mkdir -p IN && ln 16TFK* IN
mkdir -p IN && ln 16TFL* IN
mkdir -p IN && ln 16TFM* IN
mkdir -p KS && ln 13SGA* KS
mkdir -p KS && ln 13SGB* KS
mkdir -p KS && ln 13SGC* KS
mkdir -p KS && ln 13SGD* KS
mkdir -p KS && ln 13SGE* KS
mkdir -p KS && ln 13TGE* KS
mkdir -p KS && ln 14SKF* KS
mkdir -p KS && ln 14SKG* KS
mkdir -p KS && ln 14SKH* KS
mkdir -p KS && ln 14SKJ* KS
mkdir -p KS && ln 14SKK* KS
mkdir -p KS && ln 14SLF* KS
mkdir -p KS && ln 14SLG* KS
mkdir -p KS && ln 14SLH* KS
mkdir -p KS && ln 14SLJ* KS
mkdir -p KS && ln 14SLK* KS
mkdir -p KS && ln 14SMF* KS
mkdir -p KS && ln 14SMG* KS
mkdir -p KS && ln 14SMH* KS
mkdir -p KS && ln 14SMJ* KS
mkdir -p KS && ln 14SMK* KS
mkdir -p KS && ln 14SNF* KS
mkdir -p KS && ln 14SNG* KS
mkdir -p KS && ln 14SNH* KS
mkdir -p KS && ln 14SNJ* KS
mkdir -p KS && ln 14SNK* KS
mkdir -p KS && ln 14SPF* KS
mkdir -p KS && ln 14SPG* KS
mkdir -p KS && ln 14SPH* KS
mkdir -p KS && ln 14SPJ* KS
mkdir -p KS && ln 14SPK* KS
mkdir -p KS && ln 14SQF* KS
mkdir -p KS && ln 14SQG* KS
mkdir -p KS && ln 14SQH* KS
mkdir -p KS && ln 14SQJ* KS
mkdir -p KS && ln 14SQK* KS
mkdir -p KS && ln 14TKK* KS
mkdir -p KS && ln 14TLK* KS
mkdir -p KS && ln 14TMK* KS
mkdir -p KS && ln 14TNK* KS
mkdir -p KS && ln 14TPK* KS
mkdir -p KS && ln 14TQK* KS
mkdir -p KS && ln 15STA* KS
mkdir -p KS && ln 15STB* KS
mkdir -p KS && ln 15STC* KS
mkdir -p KS && ln 15STD* KS
mkdir -p KS && ln 15STE* KS
mkdir -p KS && ln 15SUA* KS
mkdir -p KS && ln 15SUB* KS
mkdir -p KS && ln 15SUC* KS
mkdir -p KS && ln 15SUD* KS
mkdir -p KS && ln 15SUE* KS
mkdir -p KS && ln 15TTE* KS
mkdir -p KY && ln 16SBF* KY
mkdir -p KY && ln 16SCF* KY
mkdir -p KY && ln 16SCG* KY
mkdir -p KY && ln 16SDF* KY
mkdir -p KY && ln 16SDG* KY
mkdir -p KY && ln 16SDH* KY
mkdir -p KY && ln 16SEF* KY
mkdir -p KY && ln 16SEG* KY
mkdir -p KY && ln 16SEH* KY
mkdir -p KY && ln 16SFF* KY
mkdir -p KY && ln 16SFG* KY
mkdir -p KY && ln 16SFH* KY
mkdir -p KY && ln 16SFJ* KY
mkdir -p KY && ln 16SGF* KY
mkdir -p KY && ln 16SGG* KY
mkdir -p KY && ln 16SGH* KY
mkdir -p KY && ln 16SGJ* KY
mkdir -p KY && ln 17SKA* KY
mkdir -p KY && ln 17SKB* KY
mkdir -p KY && ln 17SKC* KY
mkdir -p KY && ln 17SLA* KY
mkdir -p KY && ln 17SLB* KY
mkdir -p KY && ln 17SLC* KY
mkdir -p KY && ln 17SMB* KY
mkdir -p LA && ln 15RVN* LA
mkdir -p LA && ln 15RVP* LA
mkdir -p LA && ln 15RVQ* LA
mkdir -p LA && ln 15RVR* LA
mkdir -p LA && ln 15RWN* LA
mkdir -p LA && ln 15RWP* LA
mkdir -p LA && ln 15RWQ* LA
mkdir -p LA && ln 15RWR* LA
mkdir -p LA && ln 15RXN* LA
mkdir -p LA && ln 15RXP* LA
mkdir -p LA && ln 15RXQ* LA
mkdir -p LA && ln 15RXR* LA
mkdir -p LA && ln 15RYN* LA
mkdir -p LA && ln 15RYP* LA
mkdir -p LA && ln 15RYQ* LA
mkdir -p LA && ln 15SVR* LA
mkdir -p LA && ln 15SVS* LA
mkdir -p LA && ln 15SWR* LA
mkdir -p LA && ln 15SWS* LA
mkdir -p LA && ln 15SXR* LA
mkdir -p LA && ln 15SXS* LA
mkdir -p LA && ln 16RBT* LA
mkdir -p LA && ln 16RBU* LA
mkdir -p LA && ln 16RBV* LA
mkdir -p LA && ln 16RCT* LA
mkdir -p LA && ln 16RCU* LA
mkdir -p MA && ln 18TXM* MA
mkdir -p MA && ln 18TXN* MA
mkdir -p MA && ln 18TYM* MA
mkdir -p MA && ln 18TYN* MA
mkdir -p MA && ln 19TBG* MA
mkdir -p MA && ln 19TBH* MA
mkdir -p MA && ln 19TCF* MA
mkdir -p MA && ln 19TCG* MA
mkdir -p MA && ln 19TCH* MA
mkdir -p MA && ln 19TDF* MA
mkdir -p MA && ln 19TDG* MA
mkdir -p MD && ln 17SPD* MD
mkdir -p MD && ln 17SQD* MD
mkdir -p MD && ln 17SQE* MD
mkdir -p MD && ln 18STJ* MD
mkdir -p MD && ln 18STK* MD
mkdir -p MD && ln 18SUH* MD
mkdir -p MD && ln 18SUJ* MD
mkdir -p MD && ln 18SVG* MD
mkdir -p MD && ln 18SVH* MD
mkdir -p MD && ln 18SVJ* MD
mkdir -p ME && ln 19TCH* ME
mkdir -p ME && ln 19TCJ* ME
mkdir -p ME && ln 19TCK* ME
mkdir -p ME && ln 19TCL* ME
mkdir -p ME && ln 19TCM* ME
mkdir -p ME && ln 19TDJ* ME
mkdir -p ME && ln 19TDK* ME
mkdir -p ME && ln 19TDL* ME
mkdir -p ME && ln 19TDM* ME
mkdir -p ME && ln 19TDN* ME
mkdir -p ME && ln 19TEJ* ME
mkdir -p ME && ln 19TEK* ME
mkdir -p ME && ln 19TEL* ME
mkdir -p ME && ln 19TEM* ME
mkdir -p ME && ln 19TEN* ME
mkdir -p ME && ln 19TFK* ME
mkdir -p ME && ln 19TFL* ME
mkdir -p MI && ln 15TXM* MI
mkdir -p MI && ln 15TYM* MI
mkdir -p MI && ln 16TBS* MI
mkdir -p MI && ln 16TCR* MI
mkdir -p MI && ln 16TCS* MI
mkdir -p MI && ln 16TCT* MI
mkdir -p MI && ln 16TCU* MI
mkdir -p MI && ln 16TDQ* MI
mkdir -p MI && ln 16TDR* MI
mkdir -p MI && ln 16TDS* MI
mkdir -p MI && ln 16TDT* MI
mkdir -p MI && ln 16TEM* MI
mkdir -p MI && ln 16TEN* MI
mkdir -p MI && ln 16TEP* MI
mkdir -p MI && ln 16TEQ* MI
mkdir -p MI && ln 16TER* MI
mkdir -p MI && ln 16TES* MI
mkdir -p MI && ln 16TFM* MI
mkdir -p MI && ln 16TFN* MI
mkdir -p MI && ln 16TFP* MI
mkdir -p MI && ln 16TFQ* MI
mkdir -p MI && ln 16TFR* MI
mkdir -p MI && ln 16TFS* MI
mkdir -p MI && ln 16TGM* MI
mkdir -p MI && ln 16TGN* MI
mkdir -p MI && ln 16TGP* MI
mkdir -p MI && ln 16TGQ* MI
mkdir -p MI && ln 16TGR* MI
mkdir -p MI && ln 16TGS* MI
mkdir -p MI && ln 16UCU* MI
mkdir -p MI && ln 16UDU* MI
mkdir -p MI && ln 17TKG* MI
mkdir -p MI && ln 17TKH* MI
mkdir -p MI && ln 17TKJ* MI
mkdir -p MI && ln 17TKK* MI
mkdir -p MI && ln 17TKL* MI
mkdir -p MI && ln 17TKM* MI
mkdir -p MI && ln 17TLG* MI
mkdir -p MI && ln 17TLH* MI
mkdir -p MI && ln 17TLJ* MI
mkdir -p MI && ln 17TLK* MI
mkdir -p MI && ln 17TLL* MI
mkdir -p MI && ln 17TLM* MI
mkdir -p MN && ln 14TPR* MN
mkdir -p MN && ln 14TPS* MN
mkdir -p MN && ln 14TPT* MN
mkdir -p MN && ln 14TPU* MN
mkdir -p MN && ln 14TQP* MN
mkdir -p MN && ln 14TQQ* MN
mkdir -p MN && ln 14TQR* MN
mkdir -p MN && ln 14TQS* MN
mkdir -p MN && ln 14TQT* MN
mkdir -p MN && ln 14TQU* MN
mkdir -p MN && ln 14UPU* MN
mkdir -p MN && ln 14UPV* MN
mkdir -p MN && ln 14UQU* MN
mkdir -p MN && ln 14UQV* MN
mkdir -p MN && ln 15TTJ* MN
mkdir -p MN && ln 15TTK* MN
mkdir -p MN && ln 15TTL* MN
mkdir -p MN && ln 15TTM* MN
mkdir -p MN && ln 15TTN* MN
mkdir -p MN && ln 15TTP* MN
mkdir -p MN && ln 15TUJ* MN
mkdir -p MN && ln 15TUK* MN
mkdir -p MN && ln 15TUL* MN
mkdir -p MN && ln 15TUM* MN
mkdir -p MN && ln 15TUN* MN
mkdir -p MN && ln 15TUP* MN
mkdir -p MN && ln 15TVJ* MN
mkdir -p MN && ln 15TVK* MN
mkdir -p MN && ln 15TVL* MN
mkdir -p MN && ln 15TVM* MN
mkdir -p MN && ln 15TVN* MN
mkdir -p MN && ln 15TVP* MN
mkdir -p MN && ln 15TWJ* MN
mkdir -p MN && ln 15TWK* MN
mkdir -p MN && ln 15TWL* MN
mkdir -p MN && ln 15TWM* MN
mkdir -p MN && ln 15TWN* MN
mkdir -p MN && ln 15TWP* MN
mkdir -p MN && ln 15TXJ* MN
mkdir -p MN && ln 15TXN* MN
mkdir -p MN && ln 15TXP* MN
mkdir -p MN && ln 15TYN* MN
mkdir -p MN && ln 15TYP* MN
mkdir -p MN && ln 15UTP* MN
mkdir -p MN && ln 15UTQ* MN
mkdir -p MN && ln 15UUP* MN
mkdir -p MN && ln 15UUQ* MN
mkdir -p MN && ln 15UVP* MN
mkdir -p MN && ln 15UWP* MN
mkdir -p MN && ln 15UXP* MN
mkdir -p MN && ln 15UYP* MN
mkdir -p MN && ln 16TBU* MN
mkdir -p MN && ln 16TCU* MN
mkdir -p MN && ln 16UBU* MN
mkdir -p MN && ln 16UCU* MN
mkdir -p MO && ln 15SUA* MO
mkdir -p MO && ln 15SUB* MO
mkdir -p MO && ln 15SUC* MO
mkdir -p MO && ln 15SUD* MO
mkdir -p MO && ln 15SUE* MO
mkdir -p MO && ln 15SVA* MO
mkdir -p MO && ln 15SVB* MO
mkdir -p MO && ln 15SVC* MO
mkdir -p MO && ln 15SVD* MO
mkdir -p MO && ln 15SVE* MO
mkdir -p MO && ln 15SWA* MO
mkdir -p MO && ln 15SWB* MO
mkdir -p MO && ln 15SWC* MO
mkdir -p MO && ln 15SWD* MO
mkdir -p MO && ln 15SWE* MO
mkdir -p MO && ln 15SXA* MO
mkdir -p MO && ln 15SXB* MO
mkdir -p MO && ln 15SXC* MO
mkdir -p MO && ln 15SXD* MO
mkdir -p MO && ln 15SXE* MO
mkdir -p MO && ln 15SYA* MO
mkdir -p MO && ln 15SYB* MO
mkdir -p MO && ln 15SYC* MO
mkdir -p MO && ln 15SYD* MO
mkdir -p MO && ln 15SYV* MO
mkdir -p MO && ln 15TTE* MO
mkdir -p MO && ln 15TUE* MO
mkdir -p MO && ln 15TVE* MO
mkdir -p MO && ln 15TWE* MO
mkdir -p MO && ln 15TXE* MO
mkdir -p MO && ln 16SBE* MO
mkdir -p MO && ln 16SBF* MO
mkdir -p MO && ln 16SBG* MO
mkdir -p MO && ln 16SBH* MO
mkdir -p MO && ln 16SCF* MO
mkdir -p MO && ln 16SCG* MO
mkdir -p MS && ln 15RXQ* MS
mkdir -p MS && ln 15RXR* MS
mkdir -p MS && ln 15RYQ* MS
mkdir -p MS && ln 15RYR* MS
mkdir -p MS && ln 15SXR* MS
mkdir -p MS && ln 15SXS* MS
mkdir -p MS && ln 15SXT* MS
mkdir -p MS && ln 15SYR* MS
mkdir -p MS && ln 15SYS* MS
mkdir -p MS && ln 15SYT* MS
mkdir -p MS && ln 15SYU* MS
mkdir -p MS && ln 16RBA* MS
mkdir -p MS && ln 16RBU* MS
mkdir -p MS && ln 16RBV* MS
mkdir -p MS && ln 16RCA* MS
mkdir -p MS && ln 16RCU* MS
mkdir -p MS && ln 16RCV* MS
mkdir -p MS && ln 16SBA* MS
mkdir -p MS && ln 16SBB* MS
mkdir -p MS && ln 16SBC* MS
mkdir -p MS && ln 16SBD* MS
mkdir -p MS && ln 16SCA* MS
mkdir -p MS && ln 16SCB* MS
mkdir -p MS && ln 16SCC* MS
mkdir -p MS && ln 16SCD* MS
mkdir -p MT && ln 11TNN* MT
mkdir -p MT && ln 11TNP* MT
mkdir -p MT && ln 11TPL* MT
mkdir -p MT && ln 11TPM* MT
mkdir -p MT && ln 11TPN* MT
mkdir -p MT && ln 11TPP* MT
mkdir -p MT && ln 11TQL* MT
mkdir -p MT && ln 11TQM* MT
mkdir -p MT && ln 11TQN* MT
mkdir -p MT && ln 11TQP* MT
mkdir -p MT && ln 11UNP* MT
mkdir -p MT && ln 11UNQ* MT
mkdir -p MT && ln 11UPP* MT
mkdir -p MT && ln 11UPQ* MT
mkdir -p MT && ln 11UQP* MT
mkdir -p MT && ln 11UQQ* MT
mkdir -p MT && ln 12TTQ* MT
mkdir -p MT && ln 12TTR* MT
mkdir -p MT && ln 12TTS* MT
mkdir -p MT && ln 12TTT* MT
mkdir -p MT && ln 12TTU* MT
mkdir -p MT && ln 12TUQ* MT
mkdir -p MT && ln 12TUR* MT
mkdir -p MT && ln 12TUS* MT
mkdir -p MT && ln 12TUT* MT
mkdir -p MT && ln 12TUU* MT
mkdir -p MT && ln 12TVQ* MT
mkdir -p MT && ln 12TVR* MT
mkdir -p MT && ln 12TVS* MT
mkdir -p MT && ln 12TVT* MT
mkdir -p MT && ln 12TVU* MT
mkdir -p MT && ln 12TWQ* MT
mkdir -p MT && ln 12TWR* MT
mkdir -p MT && ln 12TWS* MT
mkdir -p MT && ln 12TWT* MT
mkdir -p MT && ln 12TWU* MT
mkdir -p MT && ln 12TXQ* MT
mkdir -p MT && ln 12TXR* MT
mkdir -p MT && ln 12TXS* MT
mkdir -p MT && ln 12TXT* MT
mkdir -p MT && ln 12TXU* MT
mkdir -p MT && ln 12TYQ* MT
mkdir -p MT && ln 12TYR* MT
mkdir -p MT && ln 12TYS* MT
mkdir -p MT && ln 12TYT* MT
mkdir -p MT && ln 12TYU* MT
mkdir -p MT && ln 12UTU* MT
mkdir -p MT && ln 12UTV* MT
mkdir -p MT && ln 12UUU* MT
mkdir -p MT && ln 12UUV* MT
mkdir -p MT && ln 12UVU* MT
mkdir -p MT && ln 12UVV* MT
mkdir -p MT && ln 12UWU* MT
mkdir -p MT && ln 12UWV* MT
mkdir -p MT && ln 12UXU* MT
mkdir -p MT && ln 12UXV* MT
mkdir -p MT && ln 12UYU* MT
mkdir -p MT && ln 12UYV* MT
mkdir -p MT && ln 13TBK* MT
mkdir -p MT && ln 13TBL* MT
mkdir -p MT && ln 13TBM* MT
mkdir -p MT && ln 13TBN* MT
mkdir -p MT && ln 13TBP* MT
mkdir -p MT && ln 13TCK* MT
mkdir -p MT && ln 13TCL* MT
mkdir -p MT && ln 13TCM* MT
mkdir -p MT && ln 13TCN* MT
mkdir -p MT && ln 13TCP* MT
mkdir -p MT && ln 13TDK* MT
mkdir -p MT && ln 13TDL* MT
mkdir -p MT && ln 13TDM* MT
mkdir -p MT && ln 13TDN* MT
mkdir -p MT && ln 13TDP* MT
mkdir -p MT && ln 13TEK* MT
mkdir -p MT && ln 13TEL* MT
mkdir -p MT && ln 13TEM* MT
mkdir -p MT && ln 13TEN* MT
mkdir -p MT && ln 13TEP* MT
mkdir -p MT && ln 13UBP* MT
mkdir -p MT && ln 13UBQ* MT
mkdir -p MT && ln 13UCP* MT
mkdir -p MT && ln 13UCQ* MT
mkdir -p MT && ln 13UDP* MT
mkdir -p MT && ln 13UDQ* MT
mkdir -p MT && ln 13UEP* MT
mkdir -p MT && ln 13UEQ* MT
mkdir -p NC && ln 16SGD* NC
mkdir -p NC && ln 16SGE* NC
mkdir -p NC && ln 17SKU* NC
mkdir -p NC && ln 17SKV* NC
mkdir -p NC && ln 17SLA* NC
mkdir -p NC && ln 17SLU* NC
mkdir -p NC && ln 17SLV* NC
mkdir -p NC && ln 17SMA* NC
mkdir -p NC && ln 17SMU* NC
mkdir -p NC && ln 17SMV* NC
mkdir -p NC && ln 17SNA* NC
mkdir -p NC && ln 17SNU* NC
mkdir -p NC && ln 17SNV* NC
mkdir -p NC && ln 17SPA* NC
mkdir -p NC && ln 17SPT* NC
mkdir -p NC && ln 17SPU* NC
mkdir -p NC && ln 17SPV* NC
mkdir -p NC && ln 17SQA* NC
mkdir -p NC && ln 17SQT* NC
mkdir -p NC && ln 17SQU* NC
mkdir -p NC && ln 17SQV* NC
mkdir -p NC && ln 18STC* NC
mkdir -p NC && ln 18STD* NC
mkdir -p NC && ln 18STE* NC
mkdir -p NC && ln 18STF* NC
mkdir -p NC && ln 18SUD* NC
mkdir -p NC && ln 18SUE* NC
mkdir -p NC && ln 18SUF* NC
mkdir -p NC && ln 18SVD* NC
mkdir -p NC && ln 18SVE* NC
mkdir -p NC && ln 18SVF* NC
mkdir -p ND && ln 13TEL* ND
mkdir -p ND && ln 13TEM* ND
mkdir -p ND && ln 13TEN* ND
mkdir -p ND && ln 13TEP* ND
mkdir -p ND && ln 13TFL* ND
mkdir -p ND && ln 13TFM* ND
mkdir -p ND && ln 13TFN* ND
mkdir -p ND && ln 13TFP* ND
mkdir -p ND && ln 13TGL* ND
mkdir -p ND && ln 13TGM* ND
mkdir -p ND && ln 13TGN* ND
mkdir -p ND && ln 13TGP* ND
mkdir -p ND && ln 13UEP* ND
mkdir -p ND && ln 13UEQ* ND
mkdir -p ND && ln 13UFP* ND
mkdir -p ND && ln 13UFQ* ND
mkdir -p ND && ln 13UGP* ND
mkdir -p ND && ln 13UGQ* ND
mkdir -p ND && ln 14TKR* ND
mkdir -p ND && ln 14TKS* ND
mkdir -p ND && ln 14TKT* ND
mkdir -p ND && ln 14TKU* ND
mkdir -p ND && ln 14TLR* ND
mkdir -p ND && ln 14TLS* ND
mkdir -p ND && ln 14TLT* ND
mkdir -p ND && ln 14TLU* ND
mkdir -p ND && ln 14TMR* ND
mkdir -p ND && ln 14TMS* ND
mkdir -p ND && ln 14TMT* ND
mkdir -p ND && ln 14TMU* ND
mkdir -p ND && ln 14TNR* ND
mkdir -p ND && ln 14TNS* ND
mkdir -p ND && ln 14TNT* ND
mkdir -p ND && ln 14TNU* ND
mkdir -p ND && ln 14TPR* ND
mkdir -p ND && ln 14TPS* ND
mkdir -p ND && ln 14TPT* ND
mkdir -p ND && ln 14TPU* ND
mkdir -p ND && ln 14UKU* ND
mkdir -p ND && ln 14UKV* ND
mkdir -p ND && ln 14ULU* ND
mkdir -p ND && ln 14ULV* ND
mkdir -p ND && ln 14UMU* ND
mkdir -p ND && ln 14UMV* ND
mkdir -p ND && ln 14UNU* ND
mkdir -p ND && ln 14UNV* ND
mkdir -p ND && ln 14UPU* ND
mkdir -p ND && ln 14UPV* ND
mkdir -p NE && ln 13TEF* NE
mkdir -p NE && ln 13TEG* NE
mkdir -p NE && ln 13TEH* NE
mkdir -p NE && ln 13TFF* NE
mkdir -p NE && ln 13TFG* NE
mkdir -p NE && ln 13TFH* NE
mkdir -p NE && ln 13TGE* NE
mkdir -p NE && ln 13TGF* NE
mkdir -p NE && ln 13TGG* NE
mkdir -p NE && ln 13TGH* NE
mkdir -p NE && ln 14TKK* NE
mkdir -p NE && ln 14TKL* NE
mkdir -p NE && ln 14TKM* NE
mkdir -p NE && ln 14TKN* NE
mkdir -p NE && ln 14TLK* NE
mkdir -p NE && ln 14TLL* NE
mkdir -p NE && ln 14TLM* NE
mkdir -p NE && ln 14TLN* NE
mkdir -p NE && ln 14TMK* NE
mkdir -p NE && ln 14TML* NE
mkdir -p NE && ln 14TMM* NE
mkdir -p NE && ln 14TMN* NE
mkdir -p NE && ln 14TNK* NE
mkdir -p NE && ln 14TNL* NE
mkdir -p NE && ln 14TNM* NE
mkdir -p NE && ln 14TNN* NE
mkdir -p NE && ln 14TPK* NE
mkdir -p NE && ln 14TPL* NE
mkdir -p NE && ln 14TPM* NE
mkdir -p NE && ln 14TPN* NE
mkdir -p NE && ln 14TQK* NE
mkdir -p NE && ln 14TQL* NE
mkdir -p NE && ln 14TQM* NE
mkdir -p NE && ln 14TQN* NE
mkdir -p NE && ln 15STE* NE
mkdir -p NE && ln 15SUE* NE
mkdir -p NE && ln 15TTE* NE
mkdir -p NE && ln 15TTF* NE
mkdir -p NE && ln 15TTG* NE
mkdir -p NE && ln 15TUE* NE
mkdir -p NH && ln 18TXN* NH
mkdir -p NH && ln 18TYN* NH
mkdir -p NH && ln 18TYP* NH
mkdir -p NH && ln 18TYQ* NH
mkdir -p NH && ln 19TBH* NH
mkdir -p NH && ln 19TBJ* NH
mkdir -p NH && ln 19TBK* NH
mkdir -p NH && ln 19TCH* NH
mkdir -p NH && ln 19TCJ* NH
mkdir -p NH && ln 19TCK* NH
mkdir -p NH && ln 19TCL* NH
mkdir -p NJ && ln 18SVJ* NJ
mkdir -p NJ && ln 18SVK* NJ
mkdir -p NJ && ln 18SWJ* NJ
mkdir -p NJ && ln 18SWK* NJ
mkdir -p NJ && ln 18TVK* NJ
mkdir -p NJ && ln 18TVL* NJ
mkdir -p NJ && ln 18TWK* NJ
mkdir -p NJ && ln 18TWL* NJ
mkdir -p NM && ln 12RXA* NM
mkdir -p NM && ln 12RXV* NM
mkdir -p NM && ln 12RYA* NM
mkdir -p NM && ln 12RYV* NM
mkdir -p NM && ln 12SXA* NM
mkdir -p NM && ln 12SXB* NM
mkdir -p NM && ln 12SXC* NM
mkdir -p NM && ln 12SXD* NM
mkdir -p NM && ln 12SXE* NM
mkdir -p NM && ln 12SXF* NM
mkdir -p NM && ln 12SYA* NM
mkdir -p NM && ln 12SYB* NM
mkdir -p NM && ln 12SYC* NM
mkdir -p NM && ln 12SYD* NM
mkdir -p NM && ln 12SYE* NM
mkdir -p NM && ln 12SYF* NM
mkdir -p NM && ln 13RBR* NM
mkdir -p NM && ln 13RCR* NM
mkdir -p NM && ln 13SBA* NM
mkdir -p NM && ln 13SBR* NM
mkdir -p NM && ln 13SBS* NM
mkdir -p NM && ln 13SBT* NM
mkdir -p NM && ln 13SBU* NM
mkdir -p NM && ln 13SBV* NM
mkdir -p NM && ln 13SCA* NM
mkdir -p NM && ln 13SCR* NM
mkdir -p NM && ln 13SCS* NM
mkdir -p NM && ln 13SCT* NM
mkdir -p NM && ln 13SCU* NM
mkdir -p NM && ln 13SCV* NM
mkdir -p NM && ln 13SDA* NM
mkdir -p NM && ln 13SDR* NM
mkdir -p NM && ln 13SDS* NM
mkdir -p NM && ln 13SDT* NM
mkdir -p NM && ln 13SDU* NM
mkdir -p NM && ln 13SDV* NM
mkdir -p NM && ln 13SEA* NM
mkdir -p NM && ln 13SER* NM
mkdir -p NM && ln 13SES* NM
mkdir -p NM && ln 13SET* NM
mkdir -p NM && ln 13SEU* NM
mkdir -p NM && ln 13SEV* NM
mkdir -p NM && ln 13SFA* NM
mkdir -p NM && ln 13SFR* NM
mkdir -p NM && ln 13SFS* NM
mkdir -p NM && ln 13SFT* NM
mkdir -p NM && ln 13SFU* NM
mkdir -p NM && ln 13SFV* NM
mkdir -p NV && ln 10SGJ* NV
mkdir -p NV && ln 10SGK* NV
mkdir -p NV && ln 11SKC* NV
mkdir -p NV && ln 11SKD* NV
mkdir -p NV && ln 11SKE* NV
mkdir -p NV && ln 11SLB* NV
mkdir -p NV && ln 11SLC* NV
mkdir -p NV && ln 11SLD* NV
mkdir -p NV && ln 11SLE* NV
mkdir -p NV && ln 11SMA* NV
mkdir -p NV && ln 11SMB* NV
mkdir -p NV && ln 11SMC* NV
mkdir -p NV && ln 11SMD* NV
mkdir -p NV && ln 11SME* NV
mkdir -p NV && ln 11SNA* NV
mkdir -p NV && ln 11SNB* NV
mkdir -p NV && ln 11SNC* NV
mkdir -p NV && ln 11SND* NV
mkdir -p NV && ln 11SNE* NV
mkdir -p NV && ln 11SNV* NV
mkdir -p NV && ln 11SPA* NV
mkdir -p NV && ln 11SPB* NV
mkdir -p NV && ln 11SPC* NV
mkdir -p NV && ln 11SPD* NV
mkdir -p NV && ln 11SPE* NV
mkdir -p NV && ln 11SPU* NV
mkdir -p NV && ln 11SPV* NV
mkdir -p NV && ln 11SQA* NV
mkdir -p NV && ln 11SQB* NV
mkdir -p NV && ln 11SQC* NV
mkdir -p NV && ln 11SQD* NV
mkdir -p NV && ln 11SQE* NV
mkdir -p NV && ln 11SQU* NV
mkdir -p NV && ln 11SQV* NV
mkdir -p NV && ln 11TKE* NV
mkdir -p NV && ln 11TKF* NV
mkdir -p NV && ln 11TKG* NV
mkdir -p NV && ln 11TLE* NV
mkdir -p NV && ln 11TLF* NV
mkdir -p NV && ln 11TLG* NV
mkdir -p NV && ln 11TME* NV
mkdir -p NV && ln 11TMF* NV
mkdir -p NV && ln 11TMG* NV
mkdir -p NV && ln 11TNE* NV
mkdir -p NV && ln 11TNF* NV
mkdir -p NV && ln 11TNG* NV
mkdir -p NV && ln 11TPE* NV
mkdir -p NV && ln 11TPF* NV
mkdir -p NV && ln 11TPG* NV
mkdir -p NV && ln 11TQE* NV
mkdir -p NV && ln 11TQF* NV
mkdir -p NV && ln 11TQG* NV
mkdir -p NY && ln 17TPG* NY
mkdir -p NY && ln 17TPH* NY
mkdir -p NY && ln 17TPJ* NY
mkdir -p NY && ln 17TQG* NY
mkdir -p NY && ln 17TQH* NY
mkdir -p NY && ln 17TQJ* NY
mkdir -p NY && ln 18TTM* NY
mkdir -p NY && ln 18TTN* NY
mkdir -p NY && ln 18TTP* NY
mkdir -p NY && ln 18TUM* NY
mkdir -p NY && ln 18TUN* NY
mkdir -p NY && ln 18TUP* NY
mkdir -p NY && ln 18TVL* NY
mkdir -p NY && ln 18TVM* NY
mkdir -p NY && ln 18TVN* NY
mkdir -p NY && ln 18TVP* NY
mkdir -p NY && ln 18TVQ* NY
mkdir -p NY && ln 18TWK* NY
mkdir -p NY && ln 18TWL* NY
mkdir -p NY && ln 18TWM* NY
mkdir -p NY && ln 18TWN* NY
mkdir -p NY && ln 18TWP* NY
mkdir -p NY && ln 18TWQ* NY
mkdir -p NY && ln 18TXK* NY
mkdir -p NY && ln 18TXL* NY
mkdir -p NY && ln 18TXM* NY
mkdir -p NY && ln 18TXN* NY
mkdir -p NY && ln 18TXP* NY
mkdir -p NY && ln 18TXQ* NY
mkdir -p NY && ln 18TYL* NY
mkdir -p NY && ln 19TBF* NY
mkdir -p OH && ln 16SFJ* OH
mkdir -p OH && ln 16SFK* OH
mkdir -p OH && ln 16SGH* OH
mkdir -p OH && ln 16SGJ* OH
mkdir -p OH && ln 16SGK* OH
mkdir -p OH && ln 16TFK* OH
mkdir -p OH && ln 16TFL* OH
mkdir -p OH && ln 16TFM* OH
mkdir -p OH && ln 16TGK* OH
mkdir -p OH && ln 16TGL* OH
mkdir -p OH && ln 16TGM* OH
mkdir -p OH && ln 17SKC* OH
mkdir -p OH && ln 17SKD* OH
mkdir -p OH && ln 17SKE* OH
mkdir -p OH && ln 17SLC* OH
mkdir -p OH && ln 17SLD* OH
mkdir -p OH && ln 17SLE* OH
mkdir -p OH && ln 17SMC* OH
mkdir -p OH && ln 17SMD* OH
mkdir -p OH && ln 17SME* OH
mkdir -p OH && ln 17SND* OH
mkdir -p OH && ln 17SNE* OH
mkdir -p OH && ln 17TKE* OH
mkdir -p OH && ln 17TKF* OH
mkdir -p OH && ln 17TKG* OH
mkdir -p OH && ln 17TLE* OH
mkdir -p OH && ln 17TLF* OH
mkdir -p OH && ln 17TLG* OH
mkdir -p OH && ln 17TME* OH
mkdir -p OH && ln 17TMF* OH
mkdir -p OH && ln 17TMG* OH
mkdir -p OH && ln 17TNE* OH
mkdir -p OH && ln 17TNF* OH
mkdir -p OH && ln 17TNG* OH
mkdir -p OK && ln 13SFA* OK
mkdir -p OK && ln 13SGA* OK
mkdir -p OK && ln 14SKF* OK
mkdir -p OK && ln 14SLF* OK
mkdir -p OK && ln 14SMC* OK
mkdir -p OK && ln 14SMD* OK
mkdir -p OK && ln 14SME* OK
mkdir -p OK && ln 14SMF* OK
mkdir -p OK && ln 14SNC* OK
mkdir -p OK && ln 14SND* OK
mkdir -p OK && ln 14SNE* OK
mkdir -p OK && ln 14SNF* OK
mkdir -p OK && ln 14SPC* OK
mkdir -p OK && ln 14SPD* OK
mkdir -p OK && ln 14SPE* OK
mkdir -p OK && ln 14SPF* OK
mkdir -p OK && ln 14SQC* OK
mkdir -p OK && ln 14SQD* OK
mkdir -p OK && ln 14SQE* OK
mkdir -p OK && ln 14SQF* OK
mkdir -p OK && ln 15STA* OK
mkdir -p OK && ln 15STT* OK
mkdir -p OK && ln 15STU* OK
mkdir -p OK && ln 15STV* OK
mkdir -p OK && ln 15SUA* OK
mkdir -p OK && ln 15SUT* OK
mkdir -p OK && ln 15SUU* OK
mkdir -p OK && ln 15SUV* OK
mkdir -p OR && ln 10TCM* OR
mkdir -p OR && ln 10TCN* OR
mkdir -p OR && ln 10TCP* OR
mkdir -p OR && ln 10TDM* OR
mkdir -p OR && ln 10TDN* OR
mkdir -p OR && ln 10TDP* OR
mkdir -p OR && ln 10TDQ* OR
mkdir -p OR && ln 10TDR* OR
mkdir -p OR && ln 10TDS* OR
mkdir -p OR && ln 10TEM* OR
mkdir -p OR && ln 10TEN* OR
mkdir -p OR && ln 10TEP* OR
mkdir -p OR && ln 10TEQ* OR
mkdir -p OR && ln 10TER* OR
mkdir -p OR && ln 10TES* OR
mkdir -p OR && ln 10TFM* OR
mkdir -p OR && ln 10TFN* OR
mkdir -p OR && ln 10TFP* OR
mkdir -p OR && ln 10TFQ* OR
mkdir -p OR && ln 10TFR* OR
mkdir -p OR && ln 10TGM* OR
mkdir -p OR && ln 10TGN* OR
mkdir -p OR && ln 10TGP* OR
mkdir -p OR && ln 10TGQ* OR
mkdir -p OR && ln 10TGR* OR
mkdir -p OR && ln 11TKG* OR
mkdir -p OR && ln 11TKH* OR
mkdir -p OR && ln 11TKJ* OR
mkdir -p OR && ln 11TKK* OR
mkdir -p OR && ln 11TKL* OR
mkdir -p OR && ln 11TLG* OR
mkdir -p OR && ln 11TLH* OR
mkdir -p OR && ln 11TLJ* OR
mkdir -p OR && ln 11TLK* OR
mkdir -p OR && ln 11TLL* OR
mkdir -p OR && ln 11TMG* OR
mkdir -p OR && ln 11TMH* OR
mkdir -p OR && ln 11TMJ* OR
mkdir -p OR && ln 11TMK* OR
mkdir -p OR && ln 11TML* OR
mkdir -p OR && ln 11TNJ* OR
mkdir -p OR && ln 11TNK* OR
mkdir -p OR && ln 11TNL* OR
mkdir -p PA && ln 17SND* PA
mkdir -p PA && ln 17SNE* PA
mkdir -p PA && ln 17SPD* PA
mkdir -p PA && ln 17SPE* PA
mkdir -p PA && ln 17SQD* PA
mkdir -p PA && ln 17SQE* PA
mkdir -p PA && ln 17TNE* PA
mkdir -p PA && ln 17TNF* PA
mkdir -p PA && ln 17TNG* PA
mkdir -p PA && ln 17TPE* PA
mkdir -p PA && ln 17TPF* PA
mkdir -p PA && ln 17TPG* PA
mkdir -p PA && ln 17TQE* PA
mkdir -p PA && ln 17TQF* PA
mkdir -p PA && ln 17TQG* PA
mkdir -p PA && ln 18STJ* PA
mkdir -p PA && ln 18STK* PA
mkdir -p PA && ln 18SUJ* PA
mkdir -p PA && ln 18SUK* PA
mkdir -p PA && ln 18SVJ* PA
mkdir -p PA && ln 18SVK* PA
mkdir -p PA && ln 18TTK* PA
mkdir -p PA && ln 18TTL* PA
mkdir -p PA && ln 18TTM* PA
mkdir -p PA && ln 18TUK* PA
mkdir -p PA && ln 18TUL* PA
mkdir -p PA && ln 18TUM* PA
mkdir -p PA && ln 18TVK* PA
mkdir -p PA && ln 18TVL* PA
mkdir -p PA && ln 18TVM* PA
mkdir -p PA && ln 18TWK* PA
mkdir -p PA && ln 18TWL* PA
mkdir -p RI && ln 19TBF* RI
mkdir -p RI && ln 19TBG* RI
mkdir -p RI && ln 19TCF* RI
mkdir -p RI && ln 19TCG* RI
mkdir -p SC && ln 17SKU* SC
mkdir -p SC && ln 17SLT* SC
mkdir -p SC && ln 17SLU* SC
mkdir -p SC && ln 17SMR* SC
mkdir -p SC && ln 17SMS* SC
mkdir -p SC && ln 17SMT* SC
mkdir -p SC && ln 17SMU* SC
mkdir -p SC && ln 17SNR* SC
mkdir -p SC && ln 17SNS* SC
mkdir -p SC && ln 17SNT* SC
mkdir -p SC && ln 17SNU* SC
mkdir -p SC && ln 17SPS* SC
mkdir -p SC && ln 17SPT* SC
mkdir -p SC && ln 17SPU* SC
mkdir -p SC && ln 17SQT* SC
mkdir -p SD && ln 13TEH* SD
mkdir -p SD && ln 13TEJ* SD
mkdir -p SD && ln 13TEK* SD
mkdir -p SD && ln 13TEL* SD
mkdir -p SD && ln 13TFH* SD
mkdir -p SD && ln 13TFJ* SD
mkdir -p SD && ln 13TFK* SD
mkdir -p SD && ln 13TFL* SD
mkdir -p SD && ln 13TGH* SD
mkdir -p SD && ln 13TGJ* SD
mkdir -p SD && ln 13TGK* SD
mkdir -p SD && ln 13TGL* SD
mkdir -p SD && ln 14TKN* SD
mkdir -p SD && ln 14TKP* SD
mkdir -p SD && ln 14TKQ* SD
mkdir -p SD && ln 14TKR* SD
mkdir -p SD && ln 14TLN* SD
mkdir -p SD && ln 14TLP* SD
mkdir -p SD && ln 14TLQ* SD
mkdir -p SD && ln 14TLR* SD
mkdir -p SD && ln 14TMN* SD
mkdir -p SD && ln 14TMP* SD
mkdir -p SD && ln 14TMQ* SD
mkdir -p SD && ln 14TMR* SD
mkdir -p SD && ln 14TNN* SD
mkdir -p SD && ln 14TNP* SD
mkdir -p SD && ln 14TNQ* SD
mkdir -p SD && ln 14TNR* SD
mkdir -p SD && ln 14TPN* SD
mkdir -p SD && ln 14TPP* SD
mkdir -p SD && ln 14TPQ* SD
mkdir -p SD && ln 14TPR* SD
mkdir -p SD && ln 14TQN* SD
mkdir -p SD && ln 14TQP* SD
mkdir -p SD && ln 14TQQ* SD
mkdir -p SD && ln 14TQR* SD
mkdir -p TN && ln 15SYU* TN
mkdir -p TN && ln 15SYV* TN
mkdir -p TN && ln 16SBD* TN
mkdir -p TN && ln 16SBE* TN
mkdir -p TN && ln 16SBF* TN
mkdir -p TN && ln 16SCD* TN
mkdir -p TN && ln 16SCE* TN
mkdir -p TN && ln 16SCF* TN
mkdir -p TN && ln 16SDD* TN
mkdir -p TN && ln 16SDE* TN
mkdir -p TN && ln 16SDF* TN
mkdir -p TN && ln 16SED* TN
mkdir -p TN && ln 16SEE* TN
mkdir -p TN && ln 16SEF* TN
mkdir -p TN && ln 16SFD* TN
mkdir -p TN && ln 16SFE* TN
mkdir -p TN && ln 16SFF* TN
mkdir -p TN && ln 16SGD* TN
mkdir -p TN && ln 16SGE* TN
mkdir -p TN && ln 16SGF* TN
mkdir -p TN && ln 17SKA* TN
mkdir -p TN && ln 17SKV* TN
mkdir -p TN && ln 17SLA* TN
mkdir -p TN && ln 17SLV* TN
mkdir -p TN && ln 17SMA* TN
mkdir -p TN && ln 17SMV* TN
mkdir -p TX && ln 13RCQ* TX
mkdir -p TX && ln 13RCR* TX
mkdir -p TX && ln 13RDP* TX
mkdir -p TX && ln 13RDQ* TX
mkdir -p TX && ln 13RDR* TX
mkdir -p TX && ln 13REN* TX
mkdir -p TX && ln 13REP* TX
mkdir -p TX && ln 13REQ* TX
mkdir -p TX && ln 13RER* TX
mkdir -p TX && ln 13RFN* TX
mkdir -p TX && ln 13RFP* TX
mkdir -p TX && ln 13RFQ* TX
mkdir -p TX && ln 13RFR* TX
mkdir -p TX && ln 13RGN* TX
mkdir -p TX && ln 13RGP* TX
mkdir -p TX && ln 13RGQ* TX
mkdir -p TX && ln 13RGR* TX
mkdir -p TX && ln 13SCR* TX
mkdir -p TX && ln 13SDR* TX
mkdir -p TX && ln 13SER* TX
mkdir -p TX && ln 13SFA* TX
mkdir -p TX && ln 13SFR* TX
mkdir -p TX && ln 13SFS* TX
mkdir -p TX && ln 13SFT* TX
mkdir -p TX && ln 13SFU* TX
mkdir -p TX && ln 13SFV* TX
mkdir -p TX && ln 13SGA* TX
mkdir -p TX && ln 13SGR* TX
mkdir -p TX && ln 13SGS* TX
mkdir -p TX && ln 13SGT* TX
mkdir -p TX && ln 13SGU* TX
mkdir -p TX && ln 13SGV* TX
mkdir -p TX && ln 14RKA* TX
mkdir -p TX && ln 14RKT* TX
mkdir -p TX && ln 14RKU* TX
mkdir -p TX && ln 14RKV* TX
mkdir -p TX && ln 14RLA* TX
mkdir -p TX && ln 14RLS* TX
mkdir -p TX && ln 14RLT* TX
mkdir -p TX && ln 14RLU* TX
mkdir -p TX && ln 14RLV* TX
mkdir -p TX && ln 14RMA* TX
mkdir -p TX && ln 14RMQ* TX
mkdir -p TX && ln 14RMR* TX
mkdir -p TX && ln 14RMS* TX
mkdir -p TX && ln 14RMT* TX
mkdir -p TX && ln 14RMU* TX
mkdir -p TX && ln 14RMV* TX
mkdir -p TX && ln 14RNA* TX
mkdir -p TX && ln 14RNP* TX
mkdir -p TX && ln 14RNQ* TX
mkdir -p TX && ln 14RNR* TX
mkdir -p TX && ln 14RNS* TX
mkdir -p TX && ln 14RNT* TX
mkdir -p TX && ln 14RNU* TX
mkdir -p TX && ln 14RNV* TX
mkdir -p TX && ln 14RPA* TX
mkdir -p TX && ln 14RPP* TX
mkdir -p TX && ln 14RPQ* TX
mkdir -p TX && ln 14RPR* TX
mkdir -p TX && ln 14RPS* TX
mkdir -p TX && ln 14RPT* TX
mkdir -p TX && ln 14RPU* TX
mkdir -p TX && ln 14RPV* TX
mkdir -p TX && ln 14RQA* TX
mkdir -p TX && ln 14RQR* TX
mkdir -p TX && ln 14RQS* TX
mkdir -p TX && ln 14RQT* TX
mkdir -p TX && ln 14RQU* TX
mkdir -p TX && ln 14RQV* TX
mkdir -p TX && ln 14SKA* TX
mkdir -p TX && ln 14SKB* TX
mkdir -p TX && ln 14SKC* TX
mkdir -p TX && ln 14SKD* TX
mkdir -p TX && ln 14SKE* TX
mkdir -p TX && ln 14SKF* TX
mkdir -p TX && ln 14SLA* TX
mkdir -p TX && ln 14SLB* TX
mkdir -p TX && ln 14SLC* TX
mkdir -p TX && ln 14SLD* TX
mkdir -p TX && ln 14SLE* TX
mkdir -p TX && ln 14SLF* TX
mkdir -p TX && ln 14SMA* TX
mkdir -p TX && ln 14SMB* TX
mkdir -p TX && ln 14SMC* TX
mkdir -p TX && ln 14SMD* TX
mkdir -p TX && ln 14SME* TX
mkdir -p TX && ln 14SMF* TX
mkdir -p TX && ln 14SNA* TX
mkdir -p TX && ln 14SNB* TX
mkdir -p TX && ln 14SNC* TX
mkdir -p TX && ln 14SPA* TX
mkdir -p TX && ln 14SPB* TX
mkdir -p TX && ln 14SPC* TX
mkdir -p TX && ln 14SQA* TX
mkdir -p TX && ln 14SQB* TX
mkdir -p TX && ln 14SQC* TX
mkdir -p TX && ln 15RTM* TX
mkdir -p TX && ln 15RTN* TX
mkdir -p TX && ln 15RTP* TX
mkdir -p TX && ln 15RTQ* TX
mkdir -p TX && ln 15RTR* TX
mkdir -p TX && ln 15RUN* TX
mkdir -p TX && ln 15RUP* TX
mkdir -p TX && ln 15RUQ* TX
mkdir -p TX && ln 15RUR* TX
mkdir -p TX && ln 15RVN* TX
mkdir -p TX && ln 15RVP* TX
mkdir -p TX && ln 15RVQ* TX
mkdir -p TX && ln 15RVR* TX
mkdir -p TX && ln 15STR* TX
mkdir -p TX && ln 15STS* TX
mkdir -p TX && ln 15STT* TX
mkdir -p TX && ln 15SUR* TX
mkdir -p TX && ln 15SUS* TX
mkdir -p TX && ln 15SUT* TX
mkdir -p TX && ln 15SVR* TX
mkdir -p TX && ln 15SVS* TX
mkdir -p TX && ln 15SVT* TX
mkdir -p UT && ln 11SQA* UT
mkdir -p UT && ln 11SQB* UT
mkdir -p UT && ln 11SQC* UT
mkdir -p UT && ln 11SQD* UT
mkdir -p UT && ln 11SQE* UT
mkdir -p UT && ln 11TQE* UT
mkdir -p UT && ln 11TQF* UT
mkdir -p UT && ln 11TQG* UT
mkdir -p UT && ln 12STF* UT
mkdir -p UT && ln 12STG* UT
mkdir -p UT && ln 12STH* UT
mkdir -p UT && ln 12STJ* UT
mkdir -p UT && ln 12STK* UT
mkdir -p UT && ln 12SUF* UT
mkdir -p UT && ln 12SUG* UT
mkdir -p UT && ln 12SUH* UT
mkdir -p UT && ln 12SUJ* UT
mkdir -p UT && ln 12SUK* UT
mkdir -p UT && ln 12SVF* UT
mkdir -p UT && ln 12SVG* UT
mkdir -p UT && ln 12SVH* UT
mkdir -p UT && ln 12SVJ* UT
mkdir -p UT && ln 12SVK* UT
mkdir -p UT && ln 12SWF* UT
mkdir -p UT && ln 12SWG* UT
mkdir -p UT && ln 12SWH* UT
mkdir -p UT && ln 12SWJ* UT
mkdir -p UT && ln 12SWK* UT
mkdir -p UT && ln 12SXF* UT
mkdir -p UT && ln 12SXG* UT
mkdir -p UT && ln 12SXH* UT
mkdir -p UT && ln 12SXJ* UT
mkdir -p UT && ln 12SXK* UT
mkdir -p UT && ln 12TTK* UT
mkdir -p UT && ln 12TTL* UT
mkdir -p UT && ln 12TTM* UT
mkdir -p UT && ln 12TUK* UT
mkdir -p UT && ln 12TUL* UT
mkdir -p UT && ln 12TUM* UT
mkdir -p UT && ln 12TVK* UT
mkdir -p UT && ln 12TVL* UT
mkdir -p UT && ln 12TVM* UT
mkdir -p UT && ln 12TWK* UT
mkdir -p UT && ln 12TWL* UT
mkdir -p UT && ln 12TXK* UT
mkdir -p UT && ln 12TXL* UT
mkdir -p VA && ln 17SKA* VA
mkdir -p VA && ln 17SLA* VA
mkdir -p VA && ln 17SLB* VA
mkdir -p VA && ln 17SMA* VA
mkdir -p VA && ln 17SMB* VA
mkdir -p VA && ln 17SNA* VA
mkdir -p VA && ln 17SNB* VA
mkdir -p VA && ln 17SNC* VA
mkdir -p VA && ln 17SPA* VA
mkdir -p VA && ln 17SPB* VA
mkdir -p VA && ln 17SPC* VA
mkdir -p VA && ln 17SPD* VA
mkdir -p VA && ln 17SQA* VA
mkdir -p VA && ln 17SQB* VA
mkdir -p VA && ln 17SQC* VA
mkdir -p VA && ln 17SQD* VA
mkdir -p VA && ln 18STF* VA
mkdir -p VA && ln 18STG* VA
mkdir -p VA && ln 18STH* VA
mkdir -p VA && ln 18STJ* VA
mkdir -p VA && ln 18SUF* VA
mkdir -p VA && ln 18SUG* VA
mkdir -p VA && ln 18SUH* VA
mkdir -p VA && ln 18SUJ* VA
mkdir -p VA && ln 18SVF* VA
mkdir -p VA && ln 18SVG* VA
mkdir -p VA && ln 18SVH* VA
mkdir -p VT && ln 18TXN* VT
mkdir -p VT && ln 18TXP* VT
mkdir -p VT && ln 18TXQ* VT
mkdir -p VT && ln 18TYN* VT
mkdir -p VT && ln 18TYP* VT
mkdir -p VT && ln 18TYQ* VT
mkdir -p VT && ln 19TBK* VT
mkdir -p VT && ln 19TCK* VT
mkdir -p WA && ln 10TCT* WA
mkdir -p WA && ln 10TCU* WA
mkdir -p WA && ln 10TDS* WA
mkdir -p WA && ln 10TDT* WA
mkdir -p WA && ln 10TDU* WA
mkdir -p WA && ln 10TER* WA
mkdir -p WA && ln 10TES* WA
mkdir -p WA && ln 10TET* WA
mkdir -p WA && ln 10TEU* WA
mkdir -p WA && ln 10TFR* WA
mkdir -p WA && ln 10TFS* WA
mkdir -p WA && ln 10TFT* WA
mkdir -p WA && ln 10TFU* WA
mkdir -p WA && ln 10TGR* WA
mkdir -p WA && ln 10TGS* WA
mkdir -p WA && ln 10TGT* WA
mkdir -p WA && ln 10TGU* WA
mkdir -p WA && ln 10UCU* WA
mkdir -p WA && ln 10UDU* WA
mkdir -p WA && ln 10UDV* WA
mkdir -p WA && ln 10UEU* WA
mkdir -p WA && ln 10UEV* WA
mkdir -p WA && ln 10UFU* WA
mkdir -p WA && ln 10UFV* WA
mkdir -p WA && ln 10UGU* WA
mkdir -p WA && ln 10UGV* WA
mkdir -p WA && ln 11TKL* WA
mkdir -p WA && ln 11TKM* WA
mkdir -p WA && ln 11TKN* WA
mkdir -p WA && ln 11TKP* WA
mkdir -p WA && ln 11TLL* WA
mkdir -p WA && ln 11TLM* WA
mkdir -p WA && ln 11TLN* WA
mkdir -p WA && ln 11TLP* WA
mkdir -p WA && ln 11TML* WA
mkdir -p WA && ln 11TMM* WA
mkdir -p WA && ln 11TMN* WA
mkdir -p WA && ln 11TMP* WA
mkdir -p WA && ln 11TNL* WA
mkdir -p WA && ln 11TNM* WA
mkdir -p WA && ln 11UKP* WA
mkdir -p WA && ln 11UKQ* WA
mkdir -p WA && ln 11ULP* WA
mkdir -p WA && ln 11ULQ* WA
mkdir -p WA && ln 11UMP* WA
mkdir -p WA && ln 11UMQ* WA
mkdir -p WI && ln 15TWJ* WI
mkdir -p WI && ln 15TWK* WI
mkdir -p WI && ln 15TWL* WI
mkdir -p WI && ln 15TWM* WI
mkdir -p WI && ln 15TXH* WI
mkdir -p WI && ln 15TXJ* WI
mkdir -p WI && ln 15TXK* WI
mkdir -p WI && ln 15TXL* WI
mkdir -p WI && ln 15TXM* WI
mkdir -p WI && ln 15TXN* WI
mkdir -p WI && ln 15TYH* WI
mkdir -p WI && ln 15TYJ* WI
mkdir -p WI && ln 15TYK* WI
mkdir -p WI && ln 15TYL* WI
mkdir -p WI && ln 15TYM* WI
mkdir -p WI && ln 16TBN* WI
mkdir -p WI && ln 16TBP* WI
mkdir -p WI && ln 16TBQ* WI
mkdir -p WI && ln 16TBR* WI
mkdir -p WI && ln 16TBS* WI
mkdir -p WI && ln 16TCN* WI
mkdir -p WI && ln 16TCP* WI
mkdir -p WI && ln 16TCQ* WI
mkdir -p WI && ln 16TCR* WI
mkdir -p WI && ln 16TCS* WI
mkdir -p WI && ln 16TDN* WI
mkdir -p WI && ln 16TDP* WI
mkdir -p WI && ln 16TDQ* WI
mkdir -p WI && ln 16TDR* WI
mkdir -p WI && ln 16TER* WI
mkdir -p WV && ln 17SLB* WV
mkdir -p WV && ln 17SLC* WV
mkdir -p WV && ln 17SMB* WV
mkdir -p WV && ln 17SMC* WV
mkdir -p WV && ln 17SMD* WV
mkdir -p WV && ln 17SNB* WV
mkdir -p WV && ln 17SNC* WV
mkdir -p WV && ln 17SND* WV
mkdir -p WV && ln 17SNE* WV
mkdir -p WV && ln 17SPC* WV
mkdir -p WV && ln 17SPD* WV
mkdir -p WV && ln 17SQD* WV
mkdir -p WV && ln 17TNE* WV
mkdir -p WV && ln 18STJ* WV
mkdir -p WY && ln 12TVL* WY
mkdir -p WY && ln 12TVM* WY
mkdir -p WY && ln 12TVN* WY
mkdir -p WY && ln 12TVP* WY
mkdir -p WY && ln 12TVQ* WY
mkdir -p WY && ln 12TWL* WY
mkdir -p WY && ln 12TWM* WY
mkdir -p WY && ln 12TWN* WY
mkdir -p WY && ln 12TWP* WY
mkdir -p WY && ln 12TWQ* WY
mkdir -p WY && ln 12TXL* WY
mkdir -p WY && ln 12TXM* WY
mkdir -p WY && ln 12TXN* WY
mkdir -p WY && ln 12TXP* WY
mkdir -p WY && ln 12TXQ* WY
mkdir -p WY && ln 12TYL* WY
mkdir -p WY && ln 12TYM* WY
mkdir -p WY && ln 12TYN* WY
mkdir -p WY && ln 12TYP* WY
mkdir -p WY && ln 12TYQ* WY
mkdir -p WY && ln 13TBF* WY
mkdir -p WY && ln 13TBG* WY
mkdir -p WY && ln 13TBH* WY
mkdir -p WY && ln 13TBJ* WY
mkdir -p WY && ln 13TBK* WY
mkdir -p WY && ln 13TCF* WY
mkdir -p WY && ln 13TCG* WY
mkdir -p WY && ln 13TCH* WY
mkdir -p WY && ln 13TCJ* WY
mkdir -p WY && ln 13TCK* WY
mkdir -p WY && ln 13TDF* WY
mkdir -p WY && ln 13TDG* WY
mkdir -p WY && ln 13TDH* WY
mkdir -p WY && ln 13TDJ* WY
mkdir -p WY && ln 13TDK* WY
mkdir -p WY && ln 13TEF* WY
mkdir -p WY && ln 13TEG* WY
mkdir -p WY && ln 13TEH* WY
mkdir -p WY && ln 13TEJ* WY
mkdir -p WY && ln 13TEK* WY
